import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { supabaseConfig } from "./supabase-config.js";

const supabase = createClient(supabaseConfig.url, supabaseConfig.publishableKey, {
  auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true }
});
const app = document.querySelector("#app");
const esc = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const $ = (s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={session:null,user:null,profile:null,route:"home",profileUid:null,chatId:null,chatUser:null,feed:[],stories:[],reels:[],following:new Set(),saved:new Set(),users:[],chats:[],messages:[],notifications:[],requests:[],unread:0,comments:{},profileTab:"posts",feedFilter:"all",createMode:"post",replyTo:null,typing:false,subscriptions:[]};
let renderToken=0;
const uid=()=>state.user?.id||null;
function toast(msg,type="info"){const n=document.createElement("div");n.className=`toast ${type}`;n.textContent=msg;$("#toast-root").append(n);setTimeout(()=>n.classList.add("show"),10);setTimeout(()=>{n.classList.remove("show");setTimeout(()=>n.remove(),220)},2600)}
function time(v){if(!v)return "";const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleString([], {day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function avatar(p,sz="md"){return `<div class="avatar ${sz}">${p?.photo_url?`<img src="${esc(p.photo_url)}" alt="">`:esc((p?.display_name||p?.username||"R").slice(0,1).toUpperCase())}</div>`}
function navItem(r,i,l){return `<button class="nav-item ${state.route===r?"active":""}" data-nav="${r}"><b>${i}</b><span>${l}</span></button>`}
function shell(content,active=state.route){const unread=state.unread?`<span class="badge">${state.unread>99?"99+":state.unread}</span>`:"";return `<div class="app-shell"><header class="topbar"><button class="brand" data-nav="home"><span>RAAZ</span><small>Your Chats Is Fully RAAZ</small></button><div class="top-actions"><button class="icon-btn" data-nav="notifications">♡${unread}</button><button class="icon-btn" data-nav="chats">✦</button></div></header><main class="page">${content}</main><nav class="bottom-nav">${navItem("home","⌂","Home")}${navItem("explore","⌕","Explore")}${navItem("create","+","Create")}${navItem("reels","▶","Reels")}${navItem("chats","✦","Chats")}${navItem("profile","◎","Profile")}</nav></div>`}
function back(title,route="home"){return `<div class="subbar"><button class="back" data-nav="${route}" aria-label="Back">‹</button><h2>${esc(title)}</h2><span></span></div>`}
function loading(t="Loading…"){return `<section class="center"><div class="spinner"></div><p>${esc(t)}</p></section>`}
function authView(mode="login"){return `<div class="auth-page"><div class="auth-card"><div class="logo-box">R</div><h1>RAAZ</h1><p>Your Chats Is Fully RAAZ</p><div class="auth-tabs"><button class="${mode==="login"?"selected":""}" data-auth="login">Login</button><button class="${mode==="signup"?"selected":""}" data-auth="signup">Create account</button></div><form id="auth-form">${mode==="signup"?`<label>Full name<input name="name" required autocomplete="name"></label>`:""}<label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" minlength="6" required autocomplete="current-password"></label>${mode==="signup"?`<label>Username<input name="username" required minlength="3" maxlength="24" pattern="[A-Za-z0-9_]+"></label>`:""}<button class="primary wide" type="submit">${mode==="login"?"Login to RAAZ":"Create my RAAZ account"}</button></form>${mode==="login"?`<button class="link-btn" data-reset>Forgot password?</button>`:""}<p class="security-note">Real authentication • Supabase secured</p></div></div>`}
async function profileFor(id){const {data,error}=await supabase.from("profiles").select("*").eq("id",id).maybeSingle();if(error)throw error;return data}
async function ensureProfile(){if(!uid())return null;let p=await profileFor(uid());if(!p){const base={id:uid(),username:(state.user.email?.split("@")[0]||`user${Date.now()%100000}`).toLowerCase().replace(/[^a-z0-9_]/g,"").slice(0,24)||`user${Date.now()%100000}`,display_name:state.user.user_metadata?.display_name||"RAAZ User",bio:"",photo_url:""};const {data,error}=await supabase.from("profiles").insert(base).select().single();if(error)throw error;p=data}return p}
async function boot(session){state.session=session;state.user=session.user;try{state.profile=await ensureProfile();await Promise.allSettled([loadFollowing(),loadSaved(),loadNotifications(),loadRequests(),loadUnread()]);render();subscribeRealtime()}catch(e){console.error(e);toast("Account setup failed: "+friendly(e),"error");render()}}
function friendly(e){const m=e?.message||String(e);if(/permission denied/i.test(m))return "Database permission denied. Run the V11 SQL patch in Supabase.";if(/duplicate key/i.test(m))return "This username is already in use.";return m}
async function loadFollowing(){state.following=new Set();if(!uid())return;const {data,error}=await supabase.from("follows").select("following_id").eq("follower_id",uid());if(error)throw error;(data||[]).forEach(x=>state.following.add(x.following_id))}
async function loadSaved(){state.saved=new Set();if(!uid())return;const {data,error}=await supabase.from("saved_posts").select("post_id").eq("user_id",uid());if(error)throw error;(data||[]).forEach(x=>state.saved.add(x.post_id))}
async function loadUnread(){if(!uid())return;const {data}=await supabase.from("chats").select("member_a,member_b,unread_a,unread_b").or(`member_a.eq.${uid()},member_b.eq.${uid()}`);state.unread=(data||[]).reduce((n,c)=>n+(c.member_a===uid()?c.unread_a:c.unread_b),0)}
async function loadNotifications(){if(!uid())return;const {data,error}=await supabase.from("notifications").select("*, actor:profiles!notifications_actor_id_fkey(id,username,display_name,photo_url)").eq("user_id",uid()).order("created_at",{ascending:false}).limit(50);if(!error)state.notifications=data||[]}
async function loadRequests(){if(!uid())return;const {data,error}=await supabase.from("message_requests").select("*, sender:profiles!message_requests_from_user_id_fkey(id,username,display_name,photo_url)").eq("to_user_id",uid()).eq("status","pending").order("created_at",{ascending:false});if(!error)state.requests=data||[]}
async function loadFeed(){const {data,error}=await supabase.from("posts").select("*, profile:profiles!posts_user_id_fkey(id,username,display_name,photo_url)").order("created_at",{ascending:false}).limit(100);if(error)throw error;state.feed=data||[];const {data:s}=await supabase.from("stories").select("*, profile:profiles!stories_user_id_fkey(id,username,display_name,photo_url)").gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(100);state.stories=s||[]}
async function loadReels(){const {data,error}=await supabase.from("posts").select("*, profile:profiles!posts_user_id_fkey(id,username,display_name,photo_url)").eq("type","reel").order("created_at",{ascending:false}).limit(100);if(error)throw error;state.reels=data||[]}
async function loadDiscover(term=""){let q=supabase.from("profiles").select("*").neq("id",uid()).order("created_at",{ascending:false}).limit(100);if(term){const safe=term.replace(/[%_]/g,"");q=q.or(`username.ilike.%${safe}%,display_name.ilike.%${safe}%`)}const {data,error}=await q;if(error)throw error;state.users=data||[]}
function render(){const token=++renderToken;if(!state.session){app.innerHTML=authView(state.route==="signup"?"signup":"login");bindAuth();return}let content="";if(state.route==="home")content=renderHome();else if(state.route==="explore")content=renderExplore();else if(state.route==="create")content=renderCreate();else if(state.route==="reels")content=renderReels();else if(state.route==="chats")content=renderChats();else if(state.route==="chat")content=renderChat();else if(state.route==="profile")content=renderProfile(state.profileUid||uid());else if(state.route==="settings")content=renderSettings();else if(state.route==="notifications")content=renderNotifications();else content=renderHome();app.innerHTML=shell(content,state.route);bind();if(token!==renderToken)return;loadRouteData().catch(e=>{console.error(e);toast(friendly(e),"error")})}
async function loadRouteData(){if(state.route==="home"&&state.feed.length===0){await loadFeed();render()}else if(state.route==="explore"&&state.users.length===0){await loadDiscover();render()}else if(state.route==="reels"&&state.reels.length===0){await loadReels();render()}else if(state.route==="chats"&&state.chats.length===0){await loadChats();render()}else if(state.route==="chat"&&state.chatId){await loadChat();render()}else if(state.route==="profile"&&state.profileUid){await loadProfileContent(state.profileUid);render()}}
function renderHome(){let posts=state.feed;if(state.feedFilter==="following")posts=posts.filter(p=>state.following.has(p.user_id)||p.user_id===uid());if(state.feedFilter==="saved")posts=posts.filter(p=>state.saved.has(p.id));return `<section>${renderStories()}<div class="filterbar"><button class="${state.feedFilter==="all"?"active":""}" data-filter="all">All</button><button class="${state.feedFilter==="following"?"active":""}" data-filter="following">Following</button><button class="${state.feedFilter==="saved"?"active":""}" data-filter="saved">Saved</button></div><div class="feed">${posts.length?posts.map(renderPost).join(""):loading("Loading your feed…")}</div></section>`}
function renderStories(){return `<div class="stories"><button class="story add" data-nav="create"><span>+</span><small>Your story</small></button>${state.stories.map(s=>`<button class="story" data-story="${s.id}">${avatar(s.profile,"lg")}<small>@${esc(s.profile?.username||"user")}</small></button>`).join("")}</div>`}
function renderPost(p){const mine=p.user_id===uid(),liked=false;return `<article class="post-card"><header class="post-head"><button class="post-author" data-profile="${p.user_id}">${avatar(p.profile)}<span><b>${esc(p.profile?.display_name||"RAAZ User")}</b><small>@${esc(p.profile?.username||"user")} · ${time(p.created_at)}</small></span></button><button class="more">•••</button></header>${p.text?`<p class="post-text">${esc(p.text)}</p>`:""}${p.media_url?(p.media_type?.startsWith("video")?`<video class="post-media" src="${esc(p.media_url)}" controls playsinline preload="metadata" data-view="${p.id}"></video>`:`<img class="post-media" src="${esc(p.media_url)}" alt="" loading="lazy" data-view="${p.id}">`):""}<div class="post-actions"><button data-like="${p.id}">♡ <span>${p.likes_count||0}</span></button><button data-comments="${p.id}">◯ <span>${p.comments_count||0}</span></button><button data-share="${p.id}">↗ <span>${p.shares_count||0}</span></button><button data-save="${p.id}">${state.saved.has(p.id)?"★":"☆"}</button></div><div class="post-meta">${p.views_count||0} views</div></article>`}
function renderExplore(){return `${back("Explore","home")}<div class="search-box"><input id="user-search" placeholder="Search people on RAAZ…"><button id="search-go">Search</button></div><div class="user-list">${state.users.length?state.users.map(renderUser).join(""):"<div class='muted-block'>Search or discover RAAZ users.</div>"}</div>`}
function renderUser(u){return `<button class="user-row" data-profile="${u.id}">${avatar(u)}<span><b>${esc(u.display_name)}</b><small>@${esc(u.username)}</small></span><i>${state.following.has(u.id)?"Following":"Follow"}</i></button>`}
function renderCreate(){return `${back("Create","home")}<div class="create-tabs"><button class="${state.createMode==="post"?"active":""}" data-create="post">Post</button><button class="${state.createMode==="story"?"active":""}" data-create="story">Story</button><button class="${state.createMode==="reel"?"active":""}" data-create="reel">Reel</button></div><form id="create-form" class="composer"><textarea name="text" placeholder="${state.createMode==="story"?"Story text…":"Share something with RAAZ…"}"></textarea><label class="file-pick">Choose media<input name="media" type="file" accept="${state.createMode==="reel"?"video/*":"image/*,video/*"}"></label><button class="primary wide">Publish ${state.createMode}</button><small class="hint">${state.createMode==="reel"?"Video up to 100 MB":"Images/videos up to 50 MB"}</small></form>`}
function renderReels(){return `${back("Reels","home")}<div class="reels-feed">${state.reels.length?state.reels.map(p=>`<article class="reel-card">${p.media_url?`<video src="${esc(p.media_url)}" controls playsinline loop preload="metadata" data-view="${p.id}"></video>`:""}<div class="reel-overlay"><button data-profile="${p.user_id}">@${esc(p.profile?.username||"user")}</button><p>${esc(p.text||"")}</p><span>${p.views_count||0} views · ${p.likes_count||0} likes</span></div></article>`).join(""):loading("Loading reels…")}</div>`}
async function loadChats(){const {data,error}=await supabase.from("chats").select("*").or(`member_a.eq.${uid()},member_b.eq.${uid()}`).order("updated_at",{ascending:false}).limit(100);if(error)throw error;state.chats=data||[];const ids=[...new Set(state.chats.flatMap(c=>[c.member_a,c.member_b]).filter(x=>x!==uid()))];if(ids.length){const {data:p}=await supabase.from("profiles").select("*").in("id",ids);state.chats=state.chats.map(c=>({...c,other:(p||[]).find(x=>x.id===(c.member_a===uid()?c.member_b:c.member_a))}))}}
function renderChats(){return `${back("Chats","home")}<div class="request-strip">${state.requests.length?`<button data-requests>Message requests (${state.requests.length})</button>`:""}</div><div class="chat-list">${state.chats.length?state.chats.map(c=>`<button class="chat-row" data-chat="${c.id}">${avatar(c.other)}<span><b>${esc(c.other?.display_name||"RAAZ User")}</b><small>@${esc(c.other?.username||"user")} · ${esc(c.last_message||"Start a conversation")}</small></span><i>${(c.member_a===uid()?c.unread_a:c.unread_b)||""}</i></button>`).join(""):"<div class='empty'>No chats yet. Open a profile and tap Message.</div>"}</div>`}
function renderChat(){return `${back(state.chatUser?.display_name||"Chat","chats")}<div class="chat-screen"><div id="messages" class="messages">${state.messages.map(renderMessage).join("")}</div><div class="typing-indicator">${state.typing?"typing…":""}</div><form id="message-form" class="message-form"><button type="button" id="attach">＋</button><input name="text" autocomplete="off" placeholder="Message…"><button class="send">➤</button></form></div>`}
function renderMessage(m){const mine=m.sender_id===uid();return `<div class="message-wrap ${mine?"mine":""}" data-message="${m.id}"><div class="message" data-dbl="${m.id}">${m.reply_text?`<small class="reply">${esc(m.reply_text)}</small>`:""}<span>${esc(m.deleted?"Message deleted":m.text)}</span>${m.edited?`<small> edited</small>`:""}</div><small class="message-time">${time(m.created_at)}</small></div>`}
async function loadChat(){if(!state.chatId)return;const {data:c}=await supabase.from("chats").select("*").eq("id",state.chatId).maybeSingle();if(!c)return;const other=c.member_a===uid()?c.member_b:c.member_a;state.chatUser=await profileFor(other);const {data,error}=await supabase.from("messages").select("*").eq("chat_id",state.chatId).order("created_at",{ascending:true}).limit(300);if(error)throw error;state.messages=data||[];await supabase.from("chats").update(c.member_a===uid()?{unread_a:0}:{unread_b:0}).eq("id",state.chatId);state.unread=await loadUnread()||state.unread}
function renderProfile(id){const p=state.targetProfile||state.profile;const own=id===uid();if(!p)return loading("Loading profile…");return `${back("Profile",own?"home":"explore")}<section class="profile-head">${avatar(p,"xl")}<h2>${esc(p.display_name)}</h2><p>@${esc(p.username)}</p><p class="bio">${esc(p.bio||"")}</p><div class="profile-stats"><b>${p.posts_count||0}<small>Posts</small></b><b>${p.followers_count||0}<small>Followers</small></b><b>${p.following_count||0}<small>Following</small></b></div>${own?`<div class="profile-buttons"><button data-nav="settings">Settings</button><button data-edit-profile>Edit profile</button></div>`:`<div class="profile-buttons"><button class="${state.following.has(id)?"":"primary"}" data-follow="${id}">${state.following.has(id)?"Following":"Follow"}</button><button class="primary" data-message="${id}">Message</button></div>`}</section><div class="profile-tabs"><button class="${state.profileTab==="posts"?"active":""}" data-ptab="posts">Posts</button><button class="${state.profileTab==="reels"?"active":""}" data-ptab="reels">Reels</button><button class="${state.profileTab==="analytics"?"active":""}" data-ptab="analytics">Analytics</button></div><div id="profile-content">${state.profileTab==="analytics"?renderAnalytics():renderProfileGrid()}</div>`}
function renderProfileGrid(){const arr=(state.profileContent||[]).filter(p=>state.profileTab==="reels"?p.type==="reel":p.type!=="reel");return `<div class="media-grid">${arr.length?arr.map(p=>p.media_url?(p.media_type?.startsWith("video")?`<video src="${esc(p.media_url)}" controls></video>`:`<img src="${esc(p.media_url)}" alt="">`):`<div class="text-tile">${esc(p.text||"")}</div>`).join(""):"<div class='empty'>No posts yet.</div>"}</div>`}
function renderAnalytics(){const a=state.profileContent||[];return `<div class="analytics-grid"><div><b>${a.reduce((n,p)=>n+(p.views_count||0),0)}</b><small>Views</small></div><div><b>${a.reduce((n,p)=>n+(p.likes_count||0),0)}</b><small>Likes</small></div><div><b>${a.reduce((n,p)=>n+(p.shares_count||0),0)}</b><small>Shares</small></div><div><b>${a.reduce((n,p)=>n+(p.comments_count||0),0)}</b><small>Comments</small></div></div>`}
async function loadProfileContent(id){state.targetProfile=await profileFor(id);const {data,error}=await supabase.from("posts").select("*").eq("user_id",id).order("created_at",{ascending:false}).limit(100);if(error)throw error;state.profileContent=data||[]}
function renderSettings(){return `${back("Settings","profile")}<div class="settings-list"><button data-edit-profile>👤 Edit profile</button><button data-qr>▣ RAAZ QR Code</button><button data-privacy>🔒 Privacy</button><button data-signout>↪ Log out</button></div>`}
function renderNotifications(){return `${back("Notifications","home")}<div class="notification-list">${state.notifications.length?state.notifications.map(n=>`<button class="notification" data-profile="${n.actor_id||""}">${avatar(n.actor)}<span><b>${esc(n.actor?.display_name||"RAAZ")}</b> ${esc(n.type.replaceAll("_"," "))}<small>${time(n.created_at)}</small></span></button>`).join(""):"<div class='empty'>No notifications.</div>"}</div>`}
async function uploadMedia(file,bucket){if(!file)return null;const max=50*1024*1024;if(file.size>max)throw new Error("Media is larger than 50 MB.");const ext=(file.name.split(".").pop()||"bin").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${uid()}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=supabase.storage.from(bucket).getPublicUrl(path);return data.publicUrl}
async function createContent(form){const fd=new FormData(form);const text=String(fd.get("text")||"").trim();const file=fd.get("media");const type=state.createMode;if(type==="reel"&&(!file||!file.type.startsWith("video/")))throw new Error("Reel ke liye video select karo.");let url="",mediaType="";if(file?.size){url=await uploadMedia(file,type==="story"?"stories":type==="reel"?"reels":"posts");mediaType=file.type}if(type==="story"){const {error}=await supabase.from("stories").insert({user_id:uid(),text,media_url:url,media_type:mediaType,expires_at:new Date(Date.now()+86400000).toISOString()});if(error)throw error}else{const {error}=await supabase.from("posts").insert({user_id:uid(),text,media_url:url,media_type:mediaType,type:type==="reel"?"reel":"post"});if(error)throw error;await supabase.from("profiles").update({posts_count:(state.profile.posts_count||0)+1}).eq("id",uid())}toast(`${type[0].toUpperCase()+type.slice(1)} published`,"success");state.feed=[];state.reels=[];setRoute("home")}
async function toggleFollow(target){if(target===uid())return toast("You cannot follow yourself.","error");const {data,error}=await supabase.rpc("toggle_follow",{target});if(error)throw error;if(data)state.following.add(target);else state.following.delete(target);if(state.profileUid===target){const p=await profileFor(target);state.targetProfile=p}render()}
async function toggleLike(id){const {data,error}=await supabase.rpc("toggle_like",{target:id});if(error)throw error;const p=state.feed.find(x=>x.id===id)||state.reels.find(x=>x.id===id);if(p)p.likes_count=Math.max(0,(p.likes_count||0)+(data?1:-1));render()}
async function toggleSave(id){const {data,error}=await supabase.rpc("toggle_save",{target:id});if(error)throw error;if(data)state.saved.add(id);else state.saved.delete(id);render()}
async function addComment(id,text){if(!text.trim())return;const {error}=await supabase.from("comments").insert({post_id:id,user_id:uid(),text:text.trim()});if(error)throw error;await supabase.from("posts").update({comments_count:((state.feed.find(p=>p.id===id)||{}).comments_count||0)+1}).eq("id",id);toast("Comment added","success")}
async function sharePost(id){await supabase.rpc("create_notification",{target:(state.feed.find(p=>p.id===id)||{}).user_id,kind:"post_shared",payload:{post_id:id}}).catch(()=>{});const {data:p}=await supabase.from("posts").select("shares_count").eq("id",id).single();if(p)await supabase.from("posts").update({shares_count:(p.shares_count||0)+1}).eq("id",id);toast("Share recorded","success")}
async function startChat(target){if(target===uid())return;const a=uid(),b=target;const [member_a,member_b]=a<b?[a,b]:[b,a];let {data:c,error}=await supabase.from("chats").select("*").eq("member_a",member_a).eq("member_b",member_b).maybeSingle();if(error)throw error;if(!c){const r=await supabase.from("chats").insert({member_a,member_b}).select().single();if(r.error)throw r.error;c=r.data}state.chatId=c.id;setRoute("chat",c.id)}
async function sendMessage(text){if(!text.trim()||!state.chatId)return;const {error}=await supabase.from("messages").insert({chat_id:state.chatId,sender_id:uid(),text:text.trim(),reply_to_id:state.replyTo?.id||null,reply_text:state.replyTo?.text||""});if(error)throw error;state.replyTo=null;await supabase.from("chats").update({last_message:text.trim().slice(0,120),updated_at:new Date().toISOString(),...(state.chatUser&&state.chatUser.id===state.chatUser.id?{}:{})}).eq("id",state.chatId);await loadChat();render()}
async function editMessage(id,text){const {error}=await supabase.from("messages").update({text:text.trim(),edited:true,edited_at:new Date().toISOString()}).eq("id",id).eq("sender_id",uid());if(error)throw error;await loadChat();render()}
async function deleteMessage(id){const {error}=await supabase.from("messages").update({deleted:true,text:"Message deleted",deleted_at:new Date().toISOString()}).eq("id",id).eq("sender_id",uid());if(error)throw error;await loadChat();render()}
async function reactMessage(id,emoji="❤️"){const {data:old}=await supabase.from("message_reactions").select("emoji").eq("message_id",id).eq("user_id",uid()).maybeSingle();if(old)await supabase.from("message_reactions").delete().eq("message_id",id).eq("user_id",uid());else await supabase.from("message_reactions").insert({message_id:id,user_id:uid(),emoji});toast(old?"Reaction removed":"❤️ Reacted","success")}
async function markStory(id){await supabase.rpc("add_story_view",{target:id}).catch(()=>{});toast("Story viewed")}
function setRoute(r,id=""){location.hash=id?`${r}/${id}`:r}
function parseRoute(){const [r,id]=location.hash.replace(/^#/,'').split('/');state.route=r||"home";state.profileUid=id||null;state.targetProfile=null;state.profileTab="posts"}
function subscribeRealtime(){state.subscriptions.forEach(s=>supabase.removeChannel(s));state.subscriptions=[];if(!uid())return;const ch=supabase.channel(`raaz-${uid()}`).on("postgres_changes",{event:"*",schema:"public",table:"messages"},p=>{if(state.route==="chat"&&p.new?.chat_id===state.chatId)loadChat().then(render).catch(()=>{})}).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`user_id=eq.${uid()}`},()=>loadNotifications().then(render).catch(()=>{})).on("postgres_changes",{event:"*",schema:"public",table:"chats"},()=>{loadUnread().then(()=>{if(state.route!=="chat")render()}).catch(()=>{})}).subscribe();state.subscriptions.push(ch)}
function bindAuth(){$$('[data-auth]').forEach(b=>b.onclick=()=>{state.route=b.dataset.auth;render()});const f=$("#auth-form");if(f)f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));try{if(state.route==="signup"){const username=String(d.username).trim().toLowerCase();const {data:exists}=await supabase.from("profiles").select("id").eq("username",username).maybeSingle();if(exists)throw new Error("Username is already taken.");const r=await supabase.auth.signUp({email:d.email,password:d.password,options:{data:{username,display_name:d.name}}});if(r.error)throw r.error;if(!r.data.session){toast("Account created. Check your email to confirm login.","success");state.route="login";render()}else await boot(r.data.session)}else{const r=await supabase.auth.signInWithPassword({email:d.email,password:d.password});if(r.error)throw r.error;await boot(r.data.session)}}catch(e){toast(friendly(e),"error")}};const reset=$("[data-reset]");if(reset)reset.onclick=async()=>{const email=prompt("Enter your account email:");if(!email)return;const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)toast(friendly(error),"error");else toast("Password reset email sent","success")}}
function bind(){
  $$('[data-nav]').forEach(b=>b.onclick=()=>{const r=b.dataset.nav;setRoute(r);if(r!=="profile")state.profileUid=null});
  $$('[data-profile]').forEach(b=>b.onclick=()=>{const id=b.dataset.profile;if(id)setRoute("profile",id)});
  $$('[data-filter]').forEach(b=>b.onclick=()=>{state.feedFilter=b.dataset.filter;render()});
  $$('[data-create]').forEach(b=>b.onclick=()=>{state.createMode=b.dataset.create;render()});
  const cf=$("#create-form");if(cf)cf.onsubmit=async e=>{e.preventDefault();try{await createContent(cf)}catch(x){toast(friendly(x),"error")}};
  $$('[data-follow]').forEach(b=>b.onclick=async()=>{try{await toggleFollow(b.dataset.follow)}catch(e){toast(friendly(e),"error")}});
  $$('[data-message]').forEach(b=>b.onclick=async()=>{try{await startChat(b.dataset.message)}catch(e){toast(friendly(e),"error")}});
  $$('[data-like]').forEach(b=>b.onclick=async()=>{try{await toggleLike(b.dataset.like)}catch(e){toast(friendly(e),"error")}});
  $$('[data-save]').forEach(b=>b.onclick=async()=>{try{await toggleSave(b.dataset.save)}catch(e){toast(friendly(e),"error")}});
  $$('[data-share]').forEach(b=>b.onclick=async()=>{try{await sharePost(b.dataset.share)}catch(e){toast(friendly(e),"error")}});
  $$('[data-comments]').forEach(b=>b.onclick=async()=>{const t=prompt("Write a comment:");if(t)try{await addComment(b.dataset.comments,t);render()}catch(e){toast(friendly(e),"error")}});
  $$('[data-view]').forEach(el=>{let done=false;const go=()=>{if(done)return;done=true;supabase.rpc("add_post_view",{target:el.dataset.view}).catch(()=>{})};el.addEventListener("play",go);el.addEventListener("click",go)});
  $$('[data-story]').forEach(b=>b.onclick=async()=>{const s=state.stories.find(x=>x.id===b.dataset.story);if(!s)return;await markStory(s.id);alert(`${s.profile?.display_name||"RAAZ User"}\n\n${s.text||""}`)});
  const sf=$("#user-search"),sg=$("#search-go");if(sg)sg.onclick=async()=>{try{await loadDiscover(sf.value);render()}catch(e){toast(friendly(e),"error")}};
  $$('[data-chat]').forEach(b=>b.onclick=()=>{state.chatId=b.dataset.chat;setRoute("chat",state.chatId)});
  const mf=$("#message-form");if(mf)mf.onsubmit=async e=>{e.preventDefault();const i=$("input[name=text]",mf);try{await sendMessage(i.value);i.value=""}catch(x){toast(friendly(x),"error")}};
  $$('[data-dbl]').forEach(b=>b.ondblclick=async()=>{try{await reactMessage(b.dataset.dbl)}catch(e){toast(friendly(e),"error")}});
  $$('[data-ptab]').forEach(b=>b.onclick=()=>{state.profileTab=b.dataset.ptab;render()});
  $$('[data-edit-profile]').forEach(b=>b.onclick=editProfile);
  const qr=$("[data-qr]");if(qr)qr.onclick=()=>{const url=`${location.origin}${location.pathname}#profile/${uid()}`;const w=window.open("","_blank");if(w)w.document.write(`<title>RAAZ QR Code</title><img style="max-width:90vw" src="https://api.qrserver.com/v1/create-qr-code/?size=500x500&data=${encodeURIComponent(url)}"><p>RAAZ QR Code</p>`) };
  const so=$("[data-signout]");if(so)so.onclick=()=>supabase.auth.signOut();
  const req=$("[data-requests]");if(req)req.onclick=showRequests;
  const pv=$("[data-privacy]");if(pv)pv.onclick=()=>toast("Privacy controls are being prepared for the next backend ruleset.");
  const attach=$("#attach");if(attach)attach.onclick=()=>toast("Chat media upload is next; text chat is fully realtime.");
}
async function editProfile(){const p=state.profile;const name=prompt("Display name",p.display_name||"");if(name===null)return;const username=prompt("Username",p.username||"");if(username===null)return;const bio=prompt("Bio",p.bio||"");if(bio===null)return;const u=username.trim().toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(u))return toast("Username: 3-24 letters, numbers or _","error");const {data:existing}=await supabase.from("profiles").select("id").eq("username",u).neq("id",uid()).maybeSingle();if(existing)return toast("Username already taken","error");const {data,error}=await supabase.from("profiles").update({display_name:name.trim()||"RAAZ User",username:u,bio}).eq("id",uid()).select().single();if(error)toast(friendly(error),"error");else{state.profile=data;state.targetProfile=data;toast("Profile updated","success");render()}}
async function showRequests(){if(!state.requests.length)return;const r=state.requests[0];const yes=confirm(`Accept message request from @${r.sender?.username||"user"}?`);const status=yes?"accepted":"declined";const {error}=await supabase.from("message_requests").update({status,...(yes?{accepted_at:new Date().toISOString()}:{declined_at:new Date().toISOString()})}).eq("id",r.id);if(error)return toast(friendly(error),"error");if(yes)await startChat(r.from_user_id);await loadRequests();render()}
supabase.auth.onAuthStateChange(async(event,session)=>{if(session&&(!state.session||state.session.user.id!==session.user.id))await boot(session);if(!session){state.session=null;state.user=null;state.profile=null;state.subscriptions.forEach(s=>supabase.removeChannel(s));state.subscriptions=[];state.route="login";render()}});
window.addEventListener("hashchange",()=>{parseRoute();render()});
parseRoute();
supabase.auth.getSession().then(({data})=>{if(data.session)boot(data.session);else render()}).catch(()=>render());
